swagger: "2.0"
info:
  title: REST Rating Service
  description: HTTP service for rating
  contact:
    name: mashiike
    email: ""
    url: https://github.com/mashiike/rating/issues
  version: "1.0"
host: localhost:8088
basePath: /v1
consumes:
- application/json
produces:
- application/json
paths:
  /matches:
    post:
      tags:
      - Matches
      summary: Apply match Matches
      description: Apply match and return RatingResources
      operationId: Matches#Apply match
      produces:
      - application/json
      parameters:
      - name: Apply MatchRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/MatchesApplyMatchRequestBody'
          required:
          - scores
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/MatchesApply MatchResponseBody'
      schemes:
      - http
  /players:
    post:
      tags:
      - Players
      summary: create player Players
      description: Add new player and return its RRN(Rating Resource Name).
      operationId: Players#create player
      produces:
      - application/json
      parameters:
      - name: Create PlayerRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/PlayersCreatePlayerRequestBody'
          required:
          - name
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/PlayersCreate PlayerResponseBody'
      schemes:
      - http
definitions:
  MatchesApply MatchResponseBody:
    title: 'Mediatype identifier: application/vnd.restrating.match+json; view=default'
    type: object
    properties:
      participants:
        type: array
        items:
          $ref: '#/definitions/RatingResourceResponseBody'
        example:
        - rating:
            lower: 1300
            strength: 1500
            upper: 1700
          rrn: rrn:player:XRQ85mtXnINISH25zfM0m5RlC6L2
        - rating:
            lower: 1300
            strength: 1500
            upper: 1700
          rrn: rrn:player:XRQ85mtXnINISH25zfM0m5RlC6L2
        - rating:
            lower: 1300
            strength: 1500
            upper: 1700
          rrn: rrn:player:XRQ85mtXnINISH25zfM0m5RlC6L2
        - rating:
            lower: 1300
            strength: 1500
            upper: 1700
          rrn: rrn:player:XRQ85mtXnINISH25zfM0m5RlC6L2
    description: Apply MatchResponseBody result type (default view)
    example:
      participants:
      - rating:
          lower: 1300
          strength: 1500
          upper: 1700
        rrn: rrn:player:XRQ85mtXnINISH25zfM0m5RlC6L2
      - rating:
          lower: 1300
          strength: 1500
          upper: 1700
        rrn: rrn:player:XRQ85mtXnINISH25zfM0m5RlC6L2
      - rating:
          lower: 1300
          strength: 1500
          upper: 1700
        rrn: rrn:player:XRQ85mtXnINISH25zfM0m5RlC6L2
      - rating:
          lower: 1300
          strength: 1500
          upper: 1700
        rrn: rrn:player:XRQ85mtXnINISH25zfM0m5RlC6L2
    required:
    - participants
  MatchesApplyMatchRequestBody:
    title: MatchesApplyMatchRequestBody
    type: object
    properties:
      scores:
        type: object
        example:
          rrn:player:XRQ85mtXnINISH25zfM0m5RlC6L2: 1
        additionalProperties: true
    example:
      scores:
        rrn:player:XRQ85mtXnINISH25zfM0m5RlC6L2: 1
    required:
    - scores
  PlayersCreate PlayerResponseBody:
    title: 'Mediatype identifier: application/vnd.restrating.rrn+json; view=default'
    type: object
    properties:
      rrn:
        type: string
        description: Rating Resource Name
        example: rrn:player:XRQ85mtXnINISH25zfM0m5RlC6L2
    description: Create PlayerResponseBody result type (default view)
    example:
      rrn: rrn:player:XRQ85mtXnINISH25zfM0m5RlC6L2
    required:
    - rrn
  PlayersCreatePlayerRequestBody:
    title: PlayersCreatePlayerRequestBody
    type: object
    properties:
      name:
        type: string
        example: XRQ85mtXnINISH25zfM0m5RlC6L2
    example:
      name: XRQ85mtXnINISH25zfM0m5RlC6L2
    required:
    - name
  RatingResourceResponseBody:
    title: RatingResourceResponseBody
    type: object
    properties:
      rating:
        $ref: '#/definitions/ratingResponseBody'
      rrn:
        type: string
        description: Rating Resource Name
        example: rrn:player:XRQ85mtXnINISH25zfM0m5RlC6L2
    description: RatingResource describes a strength information.
    example:
      rating:
        lower: 1300
        strength: 1500
        upper: 1700
      rrn: rrn:player:XRQ85mtXnINISH25zfM0m5RlC6L2
    required:
    - rrn
    - rating
  ratingResponseBody:
    title: ratingResponseBody
    type: object
    properties:
      lower:
        type: number
        example: 1300
        format: double
      strength:
        type: number
        example: 1500
        format: double
      upper:
        type: number
        example: 1700
        format: double
    example:
      lower: 1300
      strength: 1500
      upper: 1700
    required:
    - strength
    - lower
    - upper
externalDocs:
  description: github
  url: https://github.com/mashiike/restrating
